### ISSUE TITLE
linktree page a bit complex

### ISSUE THREAD

**Issue by tm-miha** [dyne/dyne.github.io#118]
Can https://dyne.org/linktree/ be somehow simpler? Maybe adding a section with 3 buttons/main channels and after that give the possibility to go to thematic channels?

**Comment by micolsalomone** [comment]
Done this today:
<img width="1077" alt="Screenshot 2023-09-22 alle 17 50 53" src="https://github.com/dyne/dyne.github.io/assets/26438256/c1924c16-1d71-4cf3-aba0-047deb019de9">

**Comment by micolsalomone** [comment]
All is on the same Figma: https://www.figma.com/file/eo7KxMX46OKRbdiGoPMcHk/Dyne-Website-%7C-New-Mock-and-components?type=design&node-id=350%3A4916&mode=design&t=cHKGrN39rCYNqamk-1

**Comment by tm-miha** [comment]
ciaoo do you think we can have this for the next week? we want to use it for the roll up Dyne -> Get in touch qr code 
🙏
@puria  ? 💚

**Comment by Sakrecoer** [comment]
Ciao @tm-miha, bellaaaaa!!! :sun_with_face: 

It seems there will most likely not be enough time to do that section with 3 buttons you mention in https://github.com/dyne/dyne.github.io/issues/118#issue-1908586600 

But the layout presented above by @micolsalomone will probably be on time and should mitigate the larger part of any confusion enough for now, hopefully :purple_heart:

**Comment by puria** [comment]
Implemented in #123
