### ISSUE TITLE
'Our heritage' text overlaps with software 'cards' using Safari, MacOS

### ISSUE THREAD

**Issue by EFord36** [dyne/dyne.github.io#120]
Hi,

For me, (on MacOS, Safari), the text in the 'Our heritage' section of the homepage of https://dyne.org overlaps with the first 'card' for software:

![Screenshot 2023-10-05 at 17 10 02](https://github.com/dyne/dyne.github.io/assets/20516159/cdf3dfec-f23c-4d96-bba7-6feea1e68fc5)

This doesn't happen for me when using Chrome on MacOS, or on Safari, Chrome or Edge on IOS.

Appreciate this is potentially quite low priority if it's just this combination of browser/OS that it affects, just wanted to point it out while I was looking at it.

**Comment by jaromil** [comment]
@EFord36 wow many thanks for the feedback, yes the website is not a product but a process so your report very welcome ✌️🏽

**Comment by jaromil** [comment]
Is there an easy fix for this? I don't know if it still occurs and you have any idea about it @bbtgnn or @puria or @micolsalomone .

I understand the bigger plan is to have a design system but meanwhile I wouldn't mind if `<p>nbsp;</p>` fixes it 😛

**Comment by puria** [comment]
I really don't know how to test it (no safari ;( )

**Comment by EFord36** [comment]
I actually don't see this anymore.

Maybe because of the new element with text starting "Dyne.org foundation is proud to announce"...

![Screenshot 2024-09-18 at 14 04 05](https://github.com/user-attachments/assets/9b35c784-16f9-4679-a1c6-18a9d03f9c00)
