### ISSUE TITLE
Comments about contents

### ISSUE THREAD

**Issue by puria** [dyne/dyne.github.io#13]
### Verbatim comments from @adam-burns

  Opinionated Comments on: 'who we are' block
  
  Review the section title against content.
  
  'Who we are' is not an accurate heading for this section.
  
  The section begins with a mission statement, which is best thought of as a 'why we do' 'what we do' 
  
  This is followed by three boxes of 'how we do' what we do in a way that aligns to the mission.
  
  Interdisciplinarity rollover text describes "almost 20 years of expertise in developing applications". This describes longevity, not Interdiscplinarity at all. Also "of expertise" is perhaps misleading - "years of expertise" is often used in a personal sense, or sometimes in a combined organsational sense, ie offers over a combined total of 100 years of personal development experience. Perhaps cut "expertise in".
  
  Open-source rollover box title should read Open Source?
  
  Sustainable should be Sustainability (to be a noun like previous rollover box titles). Maybe rollover text can also state aims/goals of providing long term sustainability also in open source software itself?

**Comment by puria** [comment]
Edited the copy of the pillars, can you have a look? <3 @adam-burns

**Comment by jaromil** [comment]
@puria I did here https://github.com/dyne/dyne.github.io/commit/8d4c9c0bc7ef8dfa33b6552812d68eb41af0edd8

**Comment by puria** [comment]
> @puria I did here [8d4c9c0](https://github.com/dyne/dyne.github.io/commit/8d4c9c0bc7ef8dfa33b6552812d68eb41af0edd8)

Yes! They are online!
