### ISSUE TITLE
Add fediverse identity to meta data

### ISSUE THREAD

**Issue by Sakrecoer** [dyne/dyne.github.io#163]
Note for later:

Mastodon rolled out a [new feature](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/)

This means that if we add this line to the metadata, our fedi handle will appear in any post containing a link to us on mastodon instances.

`<meta name="fediverse:creator" content="@dyne@toot.community" />`

I will look into adding it to news.dyne.org as well.

**Comment by Sakrecoer** [comment]
:heavy_check_mark: added to news.dyne.org

**Comment by jaromil** [comment]
added to `components/metatags.astro`
