### ISSUE TITLE
📈 Add analytics matomo

### ISSUE THREAD

**Issue by puria** [dyne/dyne.github.io#3]
Dajeee

**Comment by puria** [comment]
needs privacy policy before...

**Comment by Sakrecoer** [comment]
Here is a fork of the privacy policy on https://european-union.europa.eu/ which in itself is creative commons licensed.

https://github.com/Sakrecoer/pipershurvard/blob/master/privacy-policy.md

The privacy policy is made specifically for Matomo and the contains the interactive selector for it. Of course the naming needs to be changed, the contact mail and the matomo URL updated on [line 67](https://github.com/Sakrecoer/pipershurvard/blob/65483bed2362e06605abba6203d47c7ae74d988f/privacy-policy.md?plain=1#L67)

**Comment by puria** [comment]
For now closing as the will is to not have a privacy policy... so no analytics
