### ISSUE TITLE
Write new copy for donation page

### ISSUE THREAD

**Issue by Sakrecoer** [dyne/dyne.github.io#92]
Copy: 
https://pad.dyne.org/code/#/2/code/edit/7d7TtJ7TIW7pVG944AqoTeVy/

**Comment by Sakrecoer** [comment]
Prototype

**Comment by Sakrecoer** [comment]
Written, needs review

**Comment by micolsalomone** [comment]
Just made a very drafty version of visual

with sticky sidebar on desktop, still need to figure it out on mobile
<img width="1057" alt="Screenshot 2023-09-22 alle 18 43 53" src="https://github.com/dyne/dyne.github.io/assets/26438256/3c64323b-7963-4a97-b75a-0937515d55f5">

figma link: https://www.figma.com/file/eo7KxMX46OKRbdiGoPMcHk/Dyne-Website-%7C-New-Mock-and-components?type=design&node-id=350%3A6838&mode=design&t=cHKGrN39rCYNqamk-1

**Comment by jaromil** [comment]
moving forward using Hugo on https://github.com/dyne/donate

**Comment by Sakrecoer** [comment]
cosed with https://github.com/dyne/dyne.github.io/pull/171
