### ISSUE TITLE
Report hitting urls

### ISSUE THREAD

**Issue by puria** [dyne/dyne.github.io#98]
We have a lot of backlikns heritage scattered all over the interweb!
I want to know if some people hit pages, that we lost.

I see some solutions:
1. quick fix add matomo (easy and ready) drawback, should add the privacy policy to the site
2. implement some mechanism to hit a notification or save remotely when a 404 page is hitted
3. do not deploy on github pages... so we can have the `access.log` of the web server

**Comment by jaromil** [comment]
@puria a website without privacy policy is so cool... maybe deploy out of github?

**Comment by Sakrecoer** [comment]
i vote 3. also! Serving static pages is trivial in terms of ressources and is aligned with the sovereign ethics of dyne.

**Comment by puria** [comment]
This is done with a shiny new born software named broken... not yet deployed... but will be soon ;p

**Comment by puria** [comment]
deployed ;)
